config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_scope :users do
    #resources :contracts, only: [:index]
  #end

  root 'welcome#index'

  resources :users, only: [] do
    resources :guides, except: [:index]
  end

  resources :guides, only: [:index, :show] do
    member do
      put 'update_status'
    end
    collection do
      get 'search'
      get 'perform_search'
    end
    resources :contracts, only: [:new, :create]
  end

  resources :contracts, only: [:index, :show, :update] do
    member do
      post 'reject'
      post 'cancel'
      post 'finish'
    end
    resources :payments, only: [:new, :create]
  end
end

app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :guide
  belongs_to :contractor, class_name: "User", foreign_key: "user_id"
  has_one :payment
  validates_presence_of :guide, :contractor, :start_date, :end_date, :status
  validates :goals, presence: true, length: { minimum: 10 }
  validate :validate_start_date, :contracts_can_not_conflict
  enum status: [:under_analysis, :rejected, :waiting_confirmation, :canceled, :waiting_payment, :expired, :paid, :finished]

  def validate_start_date
    return if persisted?
    if start_date.present? and end_date.present?
      if start_date > end_date or start_date < DateTime.now
        errors.add(:start_date, :invalid_interval)
      end
    end
  end

  def contracts_can_not_conflict
    return if persisted?
    statuses_for_openned_contracts = [:under_analysis, :waiting_confirmation, :waiting_payment, :paid]
    openned_contracts = Contract.where("guide_id = ?", guide_id).where(status: statuses_for_openned_contracts)
    if openned_contracts.where("start_date <= ? AND end_date >= ?", start_date, start_date).any?
      errors.add(:start_date, :date_conflict)
    end
    if openned_contracts.where("start_date <= ? AND end_date >= ?", end_date, end_date).any?
      errors.add(:end_date, :date_conflict)
    end
  end

  def display_status
    I18n.t("activerecord.attributes.contract.statuses.#{self.status}")
  end
end

app/controllers/contracts_controller.rb
require 'will_paginate/array'

class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :update, :reject, :cancel, :finish]
  before_action :set_guide, only: [:new, :create]
  before_action :require_guide_or_contractor, only: [:show]
  before_action :require_guide, only: [:update, :reject, :finish]
  before_action :require_contractor, only: [:cancel]

  def index
    @statuses = params[:statuses] || []
    @start_date = search_params[:start_date]
    @end_date = search_params[:end_date]

    @contracts = current_user.contracts_as_contractor
    @contracts += current_user.contracts_as_guide if current_user.guide.present?

    #filter by status
    @contracts = @contracts.select { |contract| @statuses.include?(contract.status) } unless @statuses.blank?

    #filter by date
    if @start_date.present? and @end_date.present?
      @contracts = @contracts.select do |contract|
        contract.start_date >= @start_date and contract.end_date <= @end_date
      end
    elsif @start_date.present?
      @contracts = @contracts.select { |contract| contract.start_date >= @start_date }
    elsif @end_date.present?
      @contracts = @contracts.select { |contract| contract.end_date <= @end_date }
    end

    #paginate
    @contracts = @contracts.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @contract = Contract.new
  end

  def create
    @contract = @guide.contracts.build(create_params)
    @contract.contractor = current_user
    if @contract.save
      @contract.under_analysis!
      flash[:success] = I18n.t('messages.contract.created')
      redirect_to contracts_path
    else
      render :new
    end
  end

  def update
    @contract.update(update_params)
    @contract.waiting_confirmation!
    redirect_to contract_path(@contract)
  end

  def reject
    if @contract.under_analysis?
      @contract.rejected!
      redirect_to contract_path(@contract)
    else
      redirect_to contracts_path
    end
  end

  def cancel
    if @contract.waiting_confirmation?
      @contract.canceled!
      redirect_to contract_path(@contract)
    else
      redirect_to contracts_path
    end
  end

  def finish
    if @contract.end_date > DateTime.now
      flash[:danger] = I18n.t('messages.contract.finish.invalid_date')
      return redirect_to contracts_path
    elsif !@contract.paid?
      flash[:danger] = I18n.t('messages.contract.finish.invalid_status')
      return redirect_to contracts_path
    else
      @contract.finished!
      redirect_to contract_path(@contract)
    end
  end

  private
  def search_params
    params.permit(:start_date, :end_date, statuses: [])
  end

  def create_params
    params.require(:contract).permit(:start_date, :end_date, :goals)
  end

  def update_params
    params.require(:contract).permit(:price)
  end

  def set_contract
    @contract = Contract.find(params[:id])
  end

  def set_guide
    @guide = Guide.find(params[:guide_id])
  end

  def require_guide
    unless current_user.is_guide_of?(@contract)
      flash[:danger] = I18n.t('messages.contract.guide_required')
      redirect_to root_path
    end
  end

  def require_guide_or_contractor
    unless current_user.is_guide_of?(@contract) or current_user.is_contractor_of?(@contract)
      flash[:danger] = I18n.t('messages.contract.guide_or_contractor_required')
      redirect_to root_path
    end
  end

  def require_contractor
    unless current_user.is_contractor_of?(@contract)
      flash[:danger] = I18n.t('messages.contract.contractor_required')
      redirect_to root_path
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
  def badge_for_status(contract)
    css_classes = ["badge"]
    case contract.status.to_sym
    when :under_analysis
      css_classes << "badge-primary"
    when :waiting_confirmation
      css_classes << "badge-warning"
    when :waiting_payment
      css_classes << "badge-warning"
    when :paid
      css_classes << "badge-primary"
    when :finished
      css_classes << "badge-primary"
    when :rejected
      css_classes << "badge-danger"
    when :canceled
      css_classes << "badge-danger"
    when :expired
      css_classes << "badge-danger"
    end
    content_tag(:span, contract.display_status, class: [css_classes])
  end

  def count_contracts_by_status(status)
    count = current_user.contracts_as_contractor.where(status: status).count
    count += current_user.contracts_as_guide.where(status: status).count if current_user.guide.present?
    return count
  end
end

app/views/contracts/_contract_card.html.erb
<div class="card box-shadow margin-bottom">
  <div class="card-body">
    <div class="card-text">
      <div class="right">
        <%= badge_for_status(contract) %>
      </div>

      <div class="row">
        <!--price-->
        <div class="col-sm-6">
          <h6><%= t('contracts.index.price') %></h6>
          <%= number_to_currency contract.price, unit: "R$", separator: ",", delimiter: "" %>
        </div>
        <!--dates-->
        <div class="col-sm-6">
          <h6><%= t('contracts.index.period') %></h6>
          <%= l(contract.start_date, format: "%d/%m/%y") %>
          &#8594;
          <%= l(contract.end_date, format: "%d/%m/%y") %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <!--guide-->
          <h6><%= t('contracts.index.guide') %></h6>
          <p class="one-line-text">
            <%= link_to contract.guide.user.name, guide_path(contract.guide) %>
          </p>
        </div>
        <div class="col-sm-6">
          <!--contractor-->
          <h6><%= t('contracts.index.contractor') %></h6>
          <p class="one-line-text">
            <%= contract.contractor.name %>
          </p>
        </div>
      </div>

      <!--goals-->
      <h6><%= t('contracts.index.goals') %></h6>
      <p class="one-line-text">
        <%= contract.goals %>
      </p>

      <div class="margin-top">
        <%= link_to t('contracts.show.details'), contract_path(contract), class: 'btn btn-default btn-sm' %>

        <!--contractor options-->
        <% if current_user.is_contractor_of?(contract) %>
          <% if contract.waiting_confirmation? %>
            <%= link_to t('contracts.confirm'), new_contract_payment_path(contract), class: 'btn btn-primary btn-sm' %>
            <%= link_to t('contracts.cancel'), cancel_contract_path(contract), method: :post, class: 'btn btn-danger btn-sm pull-right' %>
          <% end %>
        <% end %>

        <!--guide options-->
        <% if current_user.is_guide_of?(contract) %>
          <% if contract.under_analysis? %>
            <%= link_to t('contracts.show.analyze'), contract_path(contract), class: 'btn btn-primary btn-sm' %>
          <% end %>

          <% if contract.paid? %>
            <%= link_to t('contracts.finish'), finish_contract_path(contract), method: :post, class: 'btn btn-primary btn-sm' %>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/contracts/_search_form.html.erb
<%= form_tag contracts_path, method: :get, class: 'form-group' do %>
  <h4><%= t('contracts.index.search.by_status') %>:</h4>
  <% Contract.statuses.map do |k, v| %>
    <div class="custom-control custom-checkbox">
      <%= check_box_tag "statuses[]", k, @statuses.include?(k), { class: 'custom-control-input', id: "status_#{k}" } %>
      <%= label_tag nil, "#{ t("activerecord.attributes.contract.statuses.#{k}") } (#{ count_contracts_by_status(k) })", { class: 'custom-control-label', for: "status_#{k}" } %>
    </div>
  <% end %>
  <hr />

  <h4><%= t('contracts.index.search.by_date') %>:</h4>

  <div class="form-group">
  <label><%= t('contracts.index.search.from') %>:</label>
    <%= date_field_tag :start_date, @start_date, class: 'form-control' %>
  </div>
  <div class="form-group">
  <label><%= t('contracts.index.search.until') %>:</label>
  <%= date_field_tag :end_date, @end_date, class: 'form-control' %>
  </div>

  <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
    <span class="fa fa-search"></span>
    <%= t('contracts.index.search.action') %>
  <% end %>
<% end %>

app/views/contracts/index.html.erb
<h1><%= t('contracts.index.title') %></h1>

<div class="row">
  <div class="col-sm-4">
    <%= render 'search_form' %>
  </div>

  <div class="col-sm-8">
    <div class="center">
      <%= will_paginate renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>

    <% @contracts.each do |contract| %>
      <%= render 'contract_card', contract: contract %>
    <% end %>

    <div class="center">
      <%= will_paginate renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
    </div>
  </div>
</div>

app/views/contracts/new.html.erb
<%= render 'shared/errors', obj: @contract %>

<div>
  <%= form_for [@guide, @contract] do |f| %>
    <div class="form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :goals %>
      <%= f.text_area :goals, class: 'form-control' %>
    </div>

    <%= f.submit t('contracts.create'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/contracts/show.html.erb
<div class="row">
  <div class="col-sm-6 center">
    <div class="card">
      <h3 class="card-header"><%= t('contracts.show.contractor') %></h3>
      <div class="card-body">
        <%= gravatar_for(@contract.contractor) %>
        <p class="margin-top"><%= @contract.contractor.name %></p>
        <small><%= @contract.contractor.email %></small>
      </div>
    </div>
  </div>
  <div class="col-sm-6 center">
    <div class="card">
      <h3 class="card-header"><%= t('contracts.show.guide') %></h3>
      <div class="card-body">
        <%= gravatar_for(@contract.guide.user) %>
        <p class="margin-top"><%= @contract.guide.user.name %></p>
        <small><%= @contract.guide.user.email %></small>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <h3><%= t('contracts.show.period') %></h3>
    <p>
      <%= l(@contract.start_date, format: "%d/%m/%y") %>
      &#8594;
      <%= l(@contract.end_date, format: "%d/%m/%y") %>
    </p>
  </div>
  <% if @contract.price.present? %>
    <div class="col-sm-6">
      <h3><%= t('contracts.show.price') %></h3>
      <p>
        <%= number_to_currency @contract.price, unit: "R$", separator: ",", delimiter: "" %>
      </p>
    </div>
  <% end %>
</div>

<div>
  <h3><%= t('contracts.show.goals') %></h3>
  <p><%= @contract.goals %></p>
</div>

<div>
  <%= badge_for_status(@contract) %>
</div>

<% if current_user.is_guide_of?(@contract) and @contract.under_analysis? %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= t('contracts.show.acceptance_question') %></h5>
      <%= form_for @contract do |f| %>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">R$</span>
            </div>
            <%= f.text_field :price, class: 'form-control' %>
          </div>
        </div>

        <%= f.submit t('contracts.accept'), class: 'btn btn-primary' %>
        <%= link_to t('contracts.reject'), reject_contract_path(@contract), method: :post, class: 'btn btn-danger pull-right' %>
      <% end %>
    </div>
  </div>
<% end %>