config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_scope :users do
    #resources :contracts, only: [:index]
  #end

  root 'welcome#index'

  resources :users, only: [] do
    resources :guides, except: [:index]
  end

  resources :guides, only: [:index, :show] do
    member do
      put 'update_status'
    end
    collection do
      get 'search'
      get 'perform_search'
    end
    resources :contracts, only: [:new, :create]
  end

  resources :contracts, only: [:index, :show, :update] do
    member do
      post 'reject'
      post 'cancel'
      post 'finish'
    end
    resources :payments, only: [:new, :create]
  end
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :user
  has_many :academic_educations
  has_one :location
  has_many :contracts
  validates :birthdate, presence: true
  validates :main_phone, presence: true, length: { minimum: 10 }
  validates :bio, presence: true, length: { minimum: 10 }
  validates :status, presence: true
  enum status: [:awaiting_for_approval, :approved, :denied]

  accepts_nested_attributes_for :academic_educations, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true

  def display_status
    I18n.t("activerecord.attributes.guide.statuses.#{self.status}")
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :update_status]

  def index
    if params[:status].present?
      @title = I18n.t('guides.index.titles.awaiting_for_approval')
      @guides = Guide.where("status = ?", Guide.statuses[params[:status]])
    else
      @title = I18n.t('guides.index.titles.all')
      @guides = Guide.all
    end
  end

  def show
  end

  def new
    @guide = current_user.build_guide
  end

  def edit
  end

  def create
    @guide = current_user.build_guide(guide_params)
    if @guide.save
      set_location
      redirect_to user_guide_path(current_user, @guide)
    else
      render :new
    end
  end

  def update
    if @guide.update(guide_params)
      @guide.awaiting_for_approval!
      set_location
      redirect_to user_guide_path(current_user, @guide)
    else
      render :edit
    end
  end

  def update_status
    if @guide.update(update_status_params)
      flash[:success] = I18n.t('messages.guide_status_updated', status: @guide.display_status)
    end
    redirect_to guides_path
  end

  def search
    @locations = Location.all
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.picture({
        #url: ActionController::Base.helpers.asset_path('guide.png'),
        url: helpers.asset_path('guide.png'),
        width: "32",
        height: "32"
      })
    end
  end

  def perform_search
    @guides = Location.near(params[:coordinates], params[:radius]).map(&:guide)
    @guides -= [current_user.guide]
    respond_to do |format|
      format.js { render partial: "guides/result" }
    end
  end

  private
  def guide_params
    params.require(:guide)
      .permit(
        :birthdate, :main_phone, :secondary_phone, :bio, 
        academic_educations_attributes: [:id, :course, :institution, :finished_in, :level],
        location_attributes: [:id, :street, :district, :city, :state]
      )
  end

  def update_status_params
    params.permit(:status)
  end

  def set_guide
    @guide = Guide.find(params[:id])
  end

  def require_admin
    unless current_user.admin?
      flash[:danger] = I18n.t('errors.admin_required')
      redirect_to root_path
    end
  end

  def set_location
    latLng = Geocoder::coordinates(@guide.location.full_address)
    if latLng.nil?
      flash[:warning] = I18n.t('messages.blank_lat_lng')
      @guide.location.update(latitude: nil, longitude: nil)
    else
      @guide.location.update(latitude: latLng.first, longitude: latLng.last)
    end
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
  def awaiting_for_approval_count
    Guide.where("status = ?", Guide.statuses[:awaiting_for_approval]).count
  end
end

app/views/guides/_academic_education_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :course %>
    <%= f.text_field :course, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :institution %>
    <%= f.text_field :institution, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :finished_in %>
    <%= f.date_field :finished_in, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :level %>
    <%= f.select :level, options_for_select(academic_educations_levels_for_select), {}, class: 'form-control' %>
  </div>

  <%= link_to_remove_association f, class: 'btn btn-danger' do %>
    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  <% end %>
</div>

app/views/guides/_form.html.erb
<%= render 'shared/errors', obj: @guide %>

<div>
  <%= form_for [current_user, @guide] do |f| %>
    <div class="form-group">
      <%= f.label :birthdate %>
      <%= f.date_field :birthdate, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :main_phone %>
      <%= f.text_field :main_phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :secondary_phone %>
      <%= f.text_field :secondary_phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_area :bio, class: 'form-control' %>
    </div>

    <ul class="nav nav-tabs">
      <li class="nav-item active">
        <a class="nav-link" data-toggle="tab" href="#academic_educations"><%= t('activerecord.attributes.guide.academic_educations') %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#location"><%= t('activerecord.attributes.guide.location') %></a>
      </li>
    </ul>

    <div class="tab-content">
      <!--academic educations-->
      <div class="tab-pane fade active in" id="academic_educations">
        <%= f.fields_for :academic_educations do |a| %>
          <%= render 'academic_education_fields', f: a %>
        <% end %>

        <div class="right margin-top">
          <%= link_to_add_association f, :academic_educations, class: 'btn btn-default' do %>
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          <% end %>
        </div>
      </div>

      <div class="tab-pane fade" id="location">
        <%= f.fields_for :location, @guide.location || Location.new do |a| %>
          <%= render 'location_form', f: a %>
        <% end %>
      </div>
    </div>

    <%= f.submit t('guides.create'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/guides/_guides.html.erb
<% @guides.each do |guide| %>
  <div class="col-md-4">
    <div class="card mb-4 box-shadow">

      <div class="card-img-top">
        <%= gravatar_for(guide.user) %>
      </div>

      <div class="card-body">
        <h4 class="card-title"> <%= guide.user.name %> </h4>
        <p class="card-text"><%= guide.bio %></p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to guide_path(guide), class: "btn btn-primary" do %>
              <i class="fa fa-eye"></i><%= t('guides.see_profile') %>
            <% end %>
          </div>
        </div>
      </div>
  
    </div>
  </div>
<% end %>

app/views/guides/_location_form.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :district %>
    <%= f.text_field :district, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
</div>

app/views/guides/_result.js.erb
$('#result').html("<%= j (render 'guides/guides.html') %>")

app/views/guides/edit.html.erb
<div class="row">
  <div class="pull-right">
    <%= link_to t('users.edit'), edit_user_registration_path(current_user), class: 'btn btn-primary' %>
  </div>
</div>

<%= render 'form' %>

app/views/guides/index.html.erb
<div class="row">
  <legend><%= @title %></legend>
  <%= render 'guides' %>
</div>

app/views/guides/new.html.erb
<%= render 'shared/errors', obj: @guide %>
<div>
  <%= form_for [current_user, @guide] do |f| %>
    <div class="form-group">
      <%= f.label :birthdate %>
      <%= f.date_field :birthdate, autofocus: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :main_phone %>
      <%= f.text_field :main_phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :secondary_phone %>
      <%= f.text_field :secondary_phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :bio %>
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
    <%= f.submit t('guides.create'), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/guides/search.html.erb
<% content_for :stylesheet do %>
  <%= stylesheet_link_tag 'pages/guides/search' %>
<% end %>

<h1><%= t('guides.search.title') %></h1>

<div class="row">
  <div class="col-sm-3">
    <div class="form-group">
      <%= t('guides.search.search_radius') %>:
      <div class="input-group">
        <%= number_field_tag :radius, 1, min: 1, class: 'form-control' %>
        <div class="input-group-append">
          <span class="input-group-text">km</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="map"></div>

<div class="row" id="result"></div>


<script src="//maps.google.com/maps/api/js?key=<%= Figaro.env.google_maps_api_key %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<%= javascript_include_tag "maps" %>
<script>
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
</script>

app/views/guides/show.html.erb
<% if current_user == @guide.user %>
  <div class="right">
    <%= link_to t('actions.edit'), edit_user_guide_path(current_user, @guide), class: 'btn btn-primary' %>
  </div>
<% end %>

<% if current_user.admin? and @guide.awaiting_for_approval? %>
  <div class="right">
    <%= link_to t('guides.approve'), update_status_guide_path(@guide, status: "approved"), method: :put, class: 'btn btn-primary' %>
    <%= link_to t('guides.deny'), update_status_guide_path(@guide, status: "denied"), method: :put, class: 'btn btn-danger' %>
  </div>
<% end %>

<% if current_user != @guide.user %>
  <div class="right">
    <%= link_to t('contracts.new'), new_guide_contract_path(@guide), class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="row">
  <div class="text-left col-sm-3">
    <%= gravatar_for(@guide.user, { size: 200 }) %>
    <h3 class="media-heading"><%= @guide.user.name %></h3>
    <h6><%= "#{ @guide.location.city }, #{ @guide.location.state }" %></h6>
    <% if @guide.approved? %>
      <span class="badge badge-primary"><%= @guide.display_status %></span>
    <% elsif @guide.awaiting_for_approval? %>
      <span class="badge badge-warning"><%= @guide.display_status %></span>
    <% else %>
      <span class="badge badge-danger"><%= @guide.display_status %></span>
    <% end %>
  </div>
  <div class="col-sm-9">
    <h3><%= t('activerecord.attributes.guide.bio') %></h3>
    <p class="text-left">
      <%= @guide.bio %>
    </p>

    <% if @guide.academic_educations.any? %>
      <h3><%= t('activerecord.attributes.guide.academic_educations') %></h3>
      <ul>
        <% @guide.academic_educations.each do |ae| %>
          <li><%= "#{ae.course} - #{ae.institution} - #{ae.display_level}" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>