config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #devise_scope :users do
    #resources :contracts, only: [:index]
  #end

  root 'welcome#index'

  resources :users, only: [] do
    resources :guides, except: [:index]
  end

  resources :guides, only: [:index, :show] do
    member do
      put 'update_status'
    end
    collection do
      get 'search'
      get 'perform_search'
    end
    resources :contracts, only: [:new, :create]
  end

  resources :contracts, only: [:index, :show, :update] do
    member do
      post 'reject'
      post 'cancel'
      post 'finish'
    end
    resources :payments, only: [:new, :create]
  end
end

app/views/layouts/_footer.html.erb
<footer>
  &copy; CEFET/RJ 2018
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <%= link_to 'Guideme', root_path, class: 'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">

    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <% if current_user.admin? %>
            <%= link_to guides_path(status: :awaiting_for_approval), class: 'nav-link' do %>
              <%= t('guides.pending_approvals') %> (<%= awaiting_for_approval_count %>)
            <% end %>
          <% end %>
        </li>
        <li class="nav-item"><%= link_to t('guides.search.link'), search_guides_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to t('contracts.index.title'), contracts_path, class: 'nav-link' %></li>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %> <span class="caret"></span>
          </a>
          <div class="dropdown-menu">
            <% if current_user.guide? or current_user.guide_candidate? %>
              <%= link_to t('guides.show'), user_guide_path(current_user, current_user.guide), class: 'dropdown-item' %>
            <% else %>
              <%= link_to t('users.edit'), edit_user_registration_path(current_user), class: 'dropdown-item' %>
            <% end %>
            <%= link_to t('users.sign_out'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>

      <% unless current_user.guide.present? %>
        <%= link_to t('guides.new'), new_user_guide_path(current_user), class: "btn btn-primary navbar-btn navbar-right" %>
      <% end %>
    <% end %>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Guideme" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <%= yield :stylesheet %>
  </head>
  <body>
  
    <%= render 'layouts/header' %>

    <main class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
    </main>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Guideme" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <%= yield :stylesheet %>
  </head>
  <body>

    <main role="main">
      <div class="row">
        <div class="col-lg-12">
          <%= render 'shared/flash' %>
          <%= yield %>
        </div>
      </div>
    </main>

    <%= javascript_include_tag "application" %>
  </body>
</html>